[package]
name = "rpc-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.21.1", features = ["full"] }
async-stream = "0.3.3"
tracing = "0.1.35"
dashmap = "5.3.4"
thiserror = "1.0.37"
futures = "0.3.24"
platform={path="../platform"}

[build-dependencies]
