[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0.35"
serde = { version = "1.0.145", features=["derive"] }
serde_json = "1.0.85"
jsonpath-rust = "0.1.6"
tracing = "0.1.36"