[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0.37"
serde = { version = "1.0.146", features=["derive"] }
serde_json = "1.0.87"
jsonpath-rust = "0.1.6"
tracing = "0.1.37"